name: "Setup build environment (ninja, ccache)"
description: "Setup the build environment. A cached build of llvm at a given ref."

inputs:
  llvm-ref:
    description: |
      LLVM Commit Ref for checkout and build. Used for ccache value and checkout.
    required: true


runs:
  using: "composite" # TODO: What is this?

  steps:
  # Checkout llvm at revision
  - uses: actions/checkout@v2
    with:
      repository: llvm/llvm-project
      ref: ${{ inputs.llvm-ref }}
      path: llvm-project
      fetch-depth: 1

  # Get ninja for cmake build.
  - name: Install Ninja
    uses: llvm/actions/install-ninja@55d844821959226fab4911f96f37071c1d4c3268

  # Setup C++ caching using ccache.
  # Cache key is a combination of OS arch and LLVM ref.
  - name: Ccache for C++ compilation
    uses: hendrikmuhs/ccache-action@v1.2
    with:
      key: ${{ runner.os }}-stablehlo_assets-${{ inputs.llvm-ref }}
      max-size: 2G

