name: Build and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    # Always regenerate once every day
    - cron:  '* 12 * * *'
  workflow_dispatch:

# Ensure that only a single job or workflow using the same
# concurrency group will run at a time. This would cancel
# any in-progress jobs in the same github workflow and github
# ref (e.g. refs/heads/main or refs/pull/<pr_number>/merge).
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Build using CMake and run tests.
# Use Cached LLVM to improve build times.
# Current setup only builds on linux.
jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os-arch: [maci-x86_64] # Consider macos-arm64 builds. FIXME: ubuntu-x86_64 not building properly
        include:
          # - os-arch: ubuntu-x86_64
          #   os: ubuntu-22.04 # Consider ubuntu version
          #   llvm-build-dir: "$GITHUB_WORKSPACE/llvm-build"
          #   stablehlo-build-dir: "$GITHUB_WORKSPACE/build"
          - os-arch: maci-x86_64 
            os: macos-latest
            llvm-build-dir: "$GITHUB_WORKSPACE/llvm-build-maci"
            stablehlo-build-dir: "$GITHUB_WORKSPACE/build-maci"
    runs-on: ${{ matrix.os }}

    steps:

    # Check out stablehlo repo
    # TODO: Confirm this will get the pull_request if action is on pull_request
    - name: Checkout stablehlo
      uses: actions/checkout@v2
      with:
        submodules: 'true' # TODO: What is this?

    - name: Get LLVM Revision
      id: llvm-revision
      shell: bash
      run: |
        echo "::set-output name=revision::$(cat ${{ github.workspace }}/build_tools/llvm_version.txt)"

    # Check out / build LLVM
    - name: Setup workspace
      uses: ./.github/actions/setup-build
      with:
        llvm-ref: ${{ steps.llvm-revision.outputs.revision }}

    # Configuration for linux
    - name: Configure and Build LLVM os-arch='${{ matrix.os-arch }}'
      shell: bash
      run: |
        ./build_tools/github_actions/ci_build_llvm.sh "$GITHUB_WORKSPACE/llvm-project/" ${{ matrix.llvm-build-dir }}

    # Configure for linux
    - name: Build and Test stablehlo os-arch='${{ matrix.os.arch }}'
      run: |
        ./build_tools/github_actions/ci_build_stablehlo.sh ${{ matrix.llvm-build-dir }} ${{ matrix.stablehlo-build-dir }}
