# Copyright 2019 The IREE Authors
#

# Keep this in sync with build_tools/scripts/lint.sh

name: Lint

on: [pull_request, push] # FIXME: just run on pull request

jobs:
  clang-format:
    runs-on: ubuntu-20.04
    steps:
      - name: Installing dependencies
        run: |
          wget https://raw.githubusercontent.com/llvm-mirror/clang/master/tools/clang-format/git-clang-format -O /tmp/git-clang-format
          chmod +x /tmp/git-clang-format
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Fetching Base Branch
        # We have to explicitly fetch the base branch as well
        run: git fetch --no-tags --prune --depth=1 origin "$GITHUB_BASE_REF:$GITHUB_BASE_REF"
      - name: Running clang-format on changed source files
        shell: bash
        run: |
          /tmp/git-clang-format "$GITHUB_BASE_REF" --binary=clang-format-12 --style=file
          git diff --exit-code
